### ISSUE TITLE
Conversion from sinusoidal lower-left corner to lon lat

### ISSUE THREAD

**Issue by etiennebr** [khufkens/MODISTools#10]
I suspect there is something wrong with the conversion from sinusoidal to angular. I'm not familiar with the sinusoidal projection, but I would suspect that the conversion using a constant is inacurate.  https://github.com/khufkens/MODISTools/blob/1adc07bd8572454bf52ba629c7cf686c60e1398b/R/coordinate_conversion.R#L108

I think a safer approach would be to build the footprint from longitude latitude. Otherwise having a few tests with different locations across latitudes would convince me :)

It would also be good to document the origin of the MODIS coordinate system parameters.  
https://github.com/khufkens/MODISTools/blob/1adc07bd8572454bf52ba629c7cf686c60e1398b/R/coordinate_conversion.R#L36-L40

ropensci/onboarding#246

**Comment by khufkens** [comment]
I've solved both issues after some detective work. Since the cellsize column doesn't change with changing latitude I think it is safe to assume that this is the grid size of the original SIN grid, for which the lower left coordinate is provided. Combining both I can then directly calculate the bounding box in SIN and convert to lat/lon.

https://github.com/khufkens/MODISTools/blob/088b222f82ddce7193a54a3ea8ba68214a7639cf/R/coordinate_conversion.R#L130

This is consistent with taking subsets as x rows and y columns from the original center pixel, rather than doing it region based (overlay of pixels), consistent with the km parameters only taking integers not floats if it was truly freeform. However, this also changes the interpretation of what is selected in lat/lon (basically the km above-below / left-right are note km in lat/lon).

**Comment by khufkens** [comment]
This is resolved imho, will re-open if disputed.
