### ISSUE TITLE
multi-band download

### ISSUE THREAD

**Issue by khufkens** [khufkens/MODISTools#12]

**Comment by JepsonNomad** [comment]
Is this a self-reminder to implement multiple bands with `mt_batch_subset()`? If so, I'm looking forward to that implementation. If not, that would be a nice addition to MODISTools! It would also be nice if users could specify a set of bands (eg `bands = c("250m_16_days_VI_Quality", "250m_16_days_NDVI", "250m_16_days_composite_day_of_the_year")`) rather than download all possible bands.

**Comment by khufkens** [comment]
This is a reminder for myself, but don't let this hold you back to implement this yourself and do a pull request.

**Comment by khufkens** [comment]
Fixed https://github.com/khufkens/MODISTools/commit/b9a04c0bf67d681687a044891f583d6aeb3acdf4
Needs unit tests.
